Fix potential bus contention
gjrchen/8-Bit-CPU-top pull request #21
Opened 2024-11-09 23:23 UTC by gjrchen

2024-11-09 23:34 UTC, Evan-Armoogan approved these changes

2024-11-10 01:17 UTC, Jeremy-Kam reviewed
I didn't work on this code, so I can't confirm with confidence that this is correct, but to me, it works out logically.

2024-11-10 01:46 UTC, SiddharthN16 approved these changes
Logic makes sense, haven't gotten to test it myself however

2024-11-10 04:52 UTC, sathworld requested changes, later dismissed
Verify that ```assign bus = (outputting_to_bus & rst_n) ? 8'bZZZZZZZZ : 8'b00000000;``` is correct

2024-11-10 04:52 UTC, sathworld commented on src/tt_um_ece298a_8_bit_cpu.v
> +    assign bus = (outputting_to_bus & rst_n) ? 8'bZZZZZZZZ : 8'b00000000;         // Initialize the bus with a known value if nothing is outputting to the bus
Are we sure its supposed to be this and not
```outputting_to_bus | rst_n```

2024-11-10 04:52 UTC, sathworld commented on src/tt_um_ece298a_8_bit_cpu.v
> +    assign bus = (outputting_to_bus & rst_n) ? 8'bZZZZZZZZ : 8'b00000000;         // Initialize the bus with a known value if nothing is outputting to the bus
this looks sus af

2024-11-10 04:52 UTC, sathworld commented on test/test.py
looks okay, besides tests are secondary to the verilog source code

2024-11-10 06:17 UTC, Penguronik commented on src/tt_um_ece298a_8_bit_cpu.v
> +    assign bus = (outputting_to_bus & rst_n) ? 8'bZZZZZZZZ : 8'b00000000;         // Initialize the bus with a known value if nothing is outputting to the bus
do we need mention of rst_n at all? I thought the values used for outputting_to_bus all already rely on rst_n

2024-11-10 06:17 UTC, Penguronik commented on src/tt_um_ece298a_8_bit_cpu.v
> +    assign bus = (outputting_to_bus & rst_n) ? 8'bZZZZZZZZ : 8'b00000000;         // Initialize the bus with a known value if nothing is outputting to the bus
actually I think we need it just for read_ui_in

2024-11-10 06:18 UTC, Penguronik commented on src/tt_um_ece298a_8_bit_cpu.v
> +    assign bus = (outputting_to_bus & rst_n) ? 8'bZZZZZZZZ : 8'b00000000;         // Initialize the bus with a known value if nothing is outputting to the bus
I think theirs is correct @sathworld since we want to drive the bus with 0s if we are resetting

2024-11-10 07:06 UTC, sathworld approved these changes
LGTM!

2024-11-10 07:06 UTC, sathworld commented on src/tt_um_ece298a_8_bit_cpu.v
> +    assign uio_out[6] = 1'b0;
why not make it an input (doesnt matter ig)

2024-11-10 07:06 UTC, sathworld commented on src/tt_um_ece298a_8_bit_cpu.v
> +    assign bus = (outputting_to_bus) ? 8'bZZZZZZZZ : 8'b00000000;         // Initialize the bus with a known value if nothing is outputting to the bus
Sure dont see why this wouldnt work

2024-11-10 07:06 UTC, sathworld commented on src/tt_um_ece298a_8_bit_cpu.v
> -    assign bus = (read_ui_in & rst_n) ? ui_in : 8'bZZZZZZZZ;                      // read_ui_in is a signal driven by CB and should be mutually exclusive with outputting to bus
Why this though

2024-11-10 07:08 UTC, sathworld commented
I think we send this

2024-11-10 07:08 UTC, merged